### ISSUE TITLE
go-to-goal

### ISSUE THREAD

**Issue by shaghayeghmzi** [hanzheteng/pioneer_mrs#1]
hi
could you please tell me how you set a specific goal for your robots? for example if you want, your robots exactly go to determine point how you control them?
thanks a lot.

**Comment by znstj** [comment]
pioneer_mrs/scripts/teleop.py 
only published cmd_vel,and not point
you can run:rostopic echo /robot1/RosAria/pose (robot1~5)

**Comment by znstj** [comment]
pioneer_mrs/scripts/teleop.py 
only published cmd_vel,and not point
you can run:rostopic echo /robot1/RosAria/pose (robot1~5)

**Comment by shaghayeghmzi** [comment]
dear @znstj 
thanks for your reply.
unfortunately for installing and running MobileSim and RosAria I cant access to the link:  http://robots.mobilerobots.com/wiki/MobileSim
http://robots.mobilerobots.com/wiki/Aria#Download_Aria


how can I install and run these nodes.
thanks a lot

**Comment by znstj** [comment]
@shaghayeghmzi 
make
sudo make install
and run :
1.run a MobileSim simulator and spawn five robots 
roslaunch pioneer_mrs mobilesim.launch
2.launch nodes on all five robots 
roslaunch pioneer_mrs multi-robot.launch machine:=mobilesim
3.launch nodes on commander 
roslaunch pioneer_mrs commander.launch

**Comment by shaghayeghmzi** [comment]
hi everyone
I have run all the steps of the configuration as launching Rosaria and installing Aria , Mobilesim but when I want to run the commands
**-roslaunch pioneer_mrs mobilesim.launch**

I have faced a warning :
robot1: TCP port 8101 unavailable. Trying again in 3 seconds...


**-roslaunch pioneer_mrs multi-robot.launch machine:=mobilesim** 

I confront with an error as: 
[ERROR] [1566967409.457132865]: RosAria: ARIA could not connect to robot! (Check ~port parameter is correct, and permissions on port device, or any errors reported above)
[FATAL] [1566967409.457173022]: RosAria: ROS node setup failed... 


I should tell you that I have changed my static IP based on wiki paged. also all my port have no permission deny but still I have faced with these errors.

**Comment by hanzheteng** [comment]
Hi @shaghayeghmzi ,

Sorry for the late reply. Currently there is no "go_to" function implemented in this repository. You can only send velocity commands to the robot. 

For formation control, it is based on a consensus algorithm, such that all robots agree with the center of the formation, and then each of them will keep a certain offset away from that point. To this end, the team formation should be static. However, I added an extra interface that can change the consensus point when the system is running online. Therefore, it "looks like" that the team is moving along some direction.

The error you mentioned is high likely on the network side. For example, the `/etc/hosts` file is incorrect and hence you cannot resolve the hostname to the right way. Please first make sure you can launch MobileSim itself without launching any robot, and then try to solve the TCP port issue.

Best Wishes,
Hanzhe
